#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
CLEAR='\033[0m'

USER=$(whoami)
FLAKE="Mikes-MBA"
SYSTEM="darwinConfigurations.$FLAKE.system"

initialize_config() {
    sudo mkdir -p /etc/nixos
    sudo chown -R $USER /etc/nixos
    sudo chmod -R +rwX /etc/nixos

    sudo mkdir -p /Users/mike/.local/share/src/nixos-config/nixos/

    cd /etc/nixos
    nix flake init -t github:michaelkeates/nixos-config#default
    sudo mv /etc/nix/nix.conf /etc/nix/nix.conf.before-nix-darwin
}

darwin_build() {
    paths=(
        "/Users/mike/.gnupg"
        "/Users/mike/.emacs.d/elpa/gnupg/S.gpg-agent"
        "/Users/mike/.emacs.d/elpa/gnupg/S.gpg-agent.browser"
        "/Users/mike/.emacs.d/elpa/gnupg/S.gpg-agent.extra"
        "/Users/mike/.emacs.d/elpa/gnupg/S.gpg-agent.ssh"
        "/Users/mike/.emacs.d/elpa/gnupg/S.scdaemon"
        "/Users/mike/Library/Application Support/Code/1.82-main.sock"
        "/Users/mike/Library/Group Containers/com.nextcloud.desktopclient/.socket"
        "/Users/mike/Library/Group Containers/BJ4HAAB9B3.ZoomClient3rd/s.zoomClient"
    )

    export NIXPKGS_ALLOW_UNFREE=1

    for path in "${paths[@]}"; do
        if [ -e "$path" ]; then
            rm -r "$path"
            echo "${GREEN}Removed $path${CLEAR}"
        else
            echo "${RED}$path does not exist. Skipping removal.${CLEAR}"
        fi
    done

    echo "${GREEN}Requesting sudo to set homebrew tap permissions...${CLEAR}"
    if [ -d "$HOME/.config/" ]; then
        sudo chmod -R 777 "$HOME/.config/"
    else
        echo "${RED}The directory $HOME/.config/ does not exist. Skipping chmod.${CLEAR}"
        sudo mkdir -p "$HOME/.config/"
        sudo chmod -R 777 "$HOME/.config/"
    fi

    sudo chmod -R 777 /opt/
    sudo chmod 777 "/Users/mike/Library/Group Containers/group.com.apple.secure-control-center-preferences/Library/Preferences/group.com.apple.secure-control-center-preferences.av.plist"

    echo "${GREEN}Starting build...${CLEAR}"

    nix --experimental-features 'nix-command flakes' build .#$SYSTEM "$@"

    echo "${GREEN}Switching to new generation...${CLEAR}"
    ./result/sw/bin/darwin-rebuild switch --flake .#$FLAKE "$@"

    sudo cp -a config/ /Users/mike/.local/share/src/nixos-config/nixos/

    echo "${GREEN}Cleaning up...${CLEAR}"
    unlink ./result

    echo "${GREEN}Done${CLEAR}"
}

initialize_config
darwin_build
