#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
CLEAR='\033[0m'

USER=$(whoami)
FLAKE="Mikes-MBA"
SYSTEM="darwinConfigurations.$FLAKE.system"

cleanup() {
  rm -rf nixos-config-main.zip nixos-config-main nixos-config
}

download_config() {
  curl -LJ0 https://github.com/michaelkeates/nixos-config/archive/main.zip -o nixos-config-main.zip
  unzip nixos-config-main.zip
  mv nixos-config-main/templates/default nixos-config
  cd nixos-config
}

setup_files() {
    sudo cp -r * /etc/nixos
    cd /etc/nixos
}

rebuild_nixos() {
    echo "${GREEN}Switching to new generation...${CLEAR}"
    ./result/sw/bin/darwin-rebuild switch --flake .#$FLAKE "$@"

    echo "${GREEN}Cleaning up...${CLEAR}"
    unlink ./result

    echo "${GREEN}Done${CLEAR}"
}

cleanup
download_config
setup_files
rebuild_nixos
cleanup