#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
CLEAR='\033[0m'

USER=$(whoami)
FLAKE="Mikes-MBA"
SYSTEM="darwinConfigurations.$FLAKE.system"

#cleanup() {
#  rm -rf nixos-config-main.zip nixos-config-main nixos-config
#  nix-store --gc
#}

download_config() {
  git clone https://github.com/michaelkeates/nixos-config.git
}

setup_files() {
    sudo cp -r nixos-config/* /etc/nixos
    cd /etc/nixos
}

rebuild_nixos() {
    nix --experimental-features 'nix-command flakes' build .#$SYSTEM "$@"

    echo "${GREEN}Switching to new generation...${CLEAR}"
    ./result/sw/bin/darwin-rebuild switch --flake .#$FLAKE "$@"

    echo "${GREEN}Cleaning up...${CLEAR}"
    unlink ./result

    echo "${GREEN}Done${CLEAR}"
}

download_config
setup_files
rebuild_nixos
#cleanup