#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
CLEAR='\033[0m'

USER=$(whoami)
FLAKE="Mikes-MBA"
SYSTEM="darwinConfigurations.$FLAKE.system"

cleanup() {
  rm -rf Users/mike/nixos-config-main.zip nixos-config-main nixos-config
  #nix-store --gc
}

download_config() {
  if [ -d "nixos-config" ]; then
    rm -rf nixos-config
  fi
  git clone https://github.com/michaelkeates/nixos-config.git
}

setup_files() {
    echo "${GREEN}Cloning Update...${CLEAR}"
    sudo cp -r nixos-config/templates/default/* /etc/nixos
    cd /etc/nixos

    echo "${GREEN}Renaming Bashrc...${CLEAR}"
    sudo rm -R /etc/bashrc-before-darwin
    sudo mv /etc/bashrc /etc/bashrc-before-darwin
}

rebuild_nixos() {
    echo "${GREEN}Updating lock file${CLEAR}"
    nix flake update

    echo "${GREEN}Begin Build...${CLEAR}"
    nix --experimental-features 'nix-command flakes' build .#$SYSTEM "$@"

    echo "${GREEN}Switching to new generation...${CLEAR}"
    ./result/sw/bin/darwin-rebuild switch --flake .#$FLAKE "$@"

    echo "${GREEN}Updating Apps from Appstore...${CLEAR}"
    sudo /opt/homebrew/bin/mas upgrade

    echo "${GREEN}Updating Apps via Brew...${CLEAR}"
    sudo /opt/homebrew/bin/mas upgrade

    echo "${GREEN}Cleaning up...${CLEAR}"
    unlink ./result

    echo "${GREEN}Done${CLEAR}"
}

download_config
setup_files
rebuild_nixos
cleanup
