#!/usr/bin/env bash
set -e

check_installer() {
  if [ -e /etc/NIXOS ]; then
    echo -e "\e[1;32mRunning in the NixOS installer environment.\e[0m"
  else
    echo -e "\e[1;31mNot running in the NixOS installer environment.\e[0m"
    exit 1
  fi
}

cleanup() {
  rm -rf nixos-config-main.zip nixos-config-main nixos-config
}

download_config() {
  curl -LJ0 https://github.com/michaelkeates/nixos-config/archive/main.zip -o nixos-config-main.zip
  unzip nixos-config-main.zip
  mv nixos-config-main/templates/default nixos-config
  cd nixos-config
}

run_disko() {
  sudo nix run --extra-experimental-features 'nix-command flakes' \
    github:nix-community/disko -- --mode zap_create_mount ./nixos/disk-config.nix
}

setup_files() {
  sudo mkdir -p /mnt/etc/nixos
  sudo cp -r * /mnt/etc/nixos
  cd /mnt/etc/nixos

  mkdir -p /root/.ssh
  touch /root/.ssh/known_hosts
  ssh-keyscan -t ed25519 github.com >> /root/.ssh/known_hosts
}

setup_ssh_keys() {
  mkdir -p /mnt/home/mike/.ssh
  chown nixos /mnt/home/mike/.ssh

  chown nixos /root/.ssh/id_ed25519_agenix{,.pub}
  cp --preserve=all /root/.ssh/id_ed25519_agenix /mnt/home/mike/.ssh/id_ed25519
  cp --preserve=all /root/.ssh/id_ed25519_agenix.pub /mnt/home/mike/.ssh/id_ed25519.pub

  chmod 600 /mnt/home/mike/.ssh/id_ed25519{,.pub}
}

link_home_dir() {
  ln -s /mnt/home/mike /home/mike # Used to grab initial secrets
}

install_nixos() {
  sudo nixos-install --flake .#nixos
  sudo chmod -R 775 /mnt/etc/nixos
}

directory_setup() {
  sudo chmod -R 777 ~/.local
  sudo chmod -R 777 ~/.config
  sudo chmod -R 777 ~/.vscode

  sudo mkdir /home/mike/.local/share/src/nixos-config/nixos/
  sudo cp -a config/ /home/mike/.local/share/src/nixos-config/nixos/
}

prompt_reboot() {
  read -p "Do you want to reboot now? (y/yes) " choice
  case "$choice" in
  y|Y|yes|YES ) echo -e "\e[1;32mRebooting...\e[0m" && sudo reboot;;
  * ) echo -e "\e[1;33mReboot skipped.\e[0m";;
  esac
}

check_installer
download_config
run_disko
setup_files
setup_ssh_keys
link_home_dir
install_nixos
cleanup
directory_setup
prompt_reboot
