#!/usr/bin/env bash
set -e

cleanup() {
    cd
    rm -rf nixos-config-main.zip nixos-config-main nixos-config
    nix-store --gc
}

download_config() {
    if [ -d "nixos-config" ]; then
        rm -rf nixos-config
    fi
    git clone https://github.com/michaelkeates/nixos-config.git

    #sudo cp -r nixos/config/login-wallpaper.jpg /home/mike/.local/share/img/wallpaper/active
    #sudo cp -r shared/config/emacs/config.org /home/mike/.local/share/src/nixos-config/shared/config/emacs/
}

setup_files() {
    cd nixos-config/templates/default
    sudo cp -r * /etc/nixos
    cd /etc/nixos

    sudo cp -r /etc/nixos/nixos/config /home/mike/.local/share/src/nixos-config/nixos/
}

rebuild_nixos() {
    #sudo nixos-rebuild switch --flake .#nixos
    #allow insecure like mailspring
    sudo NIXPKGS_ALLOW_INSECURE=1 nixos-rebuild --impure switch --flake .#nixos
}

prompt_reboot() {
    read -p "Do you want to reboot now? (y/yes) " choice
    case "$choice" in
        y|Y|yes|YES ) echo -e "\e[1;32mRebooting...\e[0m" && sudo reboot;;
        * ) echo -e "\e[1;33mReboot skipped.\e[0m";;
    esac
}

cleanup
download_config
setup_files
rebuild_nixos
cleanup
prompt_reboot
