#!/usr/bin/env bash
set -e

cleanup() {
    rm -rf nixos-config-main.zip nixos-config-main nixos-config
}

download_config() {
    curl -LJ0 https://github.com/michaelkeates/nixos-config/archive/main.zip -o nixos-config-main.zip
    unzip nixos-config-main.zip
    mv nixos-config-main/templates/default nixos-config
    cd nixos-config
}

setup_files() {
    sudo cp -r * /etc/nixos
    cd /etc/nixos

    sudo cp -r /etc/nixos/nixos/config /home/mike/.local/share/src/nixos-config/nixos/
}

rebuild_nixos() {
    sudo nixos-rebuild switch --flake .#nixos
}

cleanup
download_config
setup_files
rebuild_nixos
cleanup
